### ISSUE TITLE
Possibility to add custom CSS?

### ISSUE THREAD

**Issue by midasw** [salcido/discogs-enhancer#144]
Hello,

I was wondering if there is a way to add custom CSS rules to customize the appearance of Discogs? This could be a separate CSS file in a fixed location which the plugin could read (if you would ;) ).

Kind regards,
Midas

**Comment by salcido** [comment]
Hey, currently most of the custom CSS exists in the Dark Theme SASS file. There are a few features that use their own CSS that gets injected to the page when they're enabled but that's about it. I don't have any plans to add that as a feature but [there are a few extensions available in the Chrome Store](https://chrome.google.com/webstore/search/custom%20css?_category=extensions) that do what you're asking about.
