### ISSUE TITLE
Possible to change the Inventory link to have the same settings each time?

### ISSUE THREAD

**Issue by unpaidloanvictim** [salcido/discogs-enhancer#152]
I sell a fair deal on Discogs, and every time I open my inventory to search for something I usually do so before remembering to set it to For Sale items only instead of just everything, and often I'll forget I have the page set to show 50 results instead of 1000, which I usually don't notice right away (did I mention I'm kinda dumb, haha), is it possible to change the Inventory link so that when I click it in the site it's already set up to just show items for sale? I've got a bookmark for that, but it's in a folder with some other important pages from the site so I generally don't think to use it. Thanks! I love the app btw, super helpful.

**Comment by salcido** [comment]
@unpaidloanvictim Hey, sorry for the long delay in getting back to you. There's not currently a way to do this with the extension but you can use another extension called Tampermonkey to do it. Basically install Tampermonkey, Click "Create a new script" and copy/paste this code in and save it. That should do what you're looking for. ✌️

```
// ==UserScript==
// @name         Show For Sale Items in Inventory
// @namespace    https://www.discogs-enhancer.com
// @version      0.1
// @description  Sets the initial inventory page to show only For Sale items with 1000 results
// @author       Matthew Salcido (discogs.enhancer@gmail.com)
// @match        https://www.discogs.com/*
// @grant        none
// ==/UserScript==
(function() {
    function waitForElement(selector) {
        return new Promise(resolve => {
            if (document.querySelector(selector)) {
                return resolve(document.querySelector(selector));
            }
 
            let observer = new MutationObserver(() => {
                if (document.querySelector(selector)) {
                    resolve(document.querySelector(selector));
                    observer.disconnect();
                }
            });
 
            observer.observe(document.body, {
                childList: true,
                subtree: true
            });
        });
    }
 
    waitForElement('a[href*="/sell/manage"]').then(() => {
        document.querySelectorAll('a[href*="/sell/manage"]').forEach(a => { a.href = '/sell/manage?page=1&status=For+Sale&limit=1000'; })
    });
})();
```

**Comment by unpaidloanvictim** [comment]
Awesome, thanks so much! I think I've tried something like that years ago,
might have been Greasemonkey, but code just isn't for me so I gave up
quick, haha.
