### ISSUE TITLE
Request: Sort a Items For Sale page by price including shipping.

### ISSUE THREAD

**Issue by siquick** [salcido/discogs-enhancer#155]
As the title says, would love to be able to sort items for sale by total price.

e.g. on this page

https://www.discogs.com/sell/mywants

**Comment by salcido** [comment]
@siquick Hey, sorry but it's not possible to do with the extension. [The wantlist API does not return Marketplace-related data](https://www.discogs.com/developers#page:user-wantlist,header:user-wantlist-wantlist) so there's no way to sort while including shipping.
