### ISSUE TITLE
Error fetching price average

### ISSUE THREAD

**Issue by davidkmiller** [salcido/discogs-enhancer#161]
Show Price Comparison & Statistics is today showing "Error getting price data." - it was working yesterday

**Comment by salcido** [comment]
Thanks! This is because the URL structure changed yesterday afternoon: https://www.discogs.com/forum/thread/899830

The fix has been submitted to the Chrome Store - just waiting on approval.

**Comment by davidkmiller** [comment]
Good stuff, I thought it would something like this or an API change (although you'd expect that be version controlled and backward compatible)

**Comment by salcido** [comment]
Yeah, I think the backwards compatibility is the redirect that was added. 

In other news, I'm working on a new endpoint for discogs-enhancer.com that will display any known issues like this in the extensions popup window so users will have a heads up (and also not assume I broke something lol)

**Comment by davidkmiller** [comment]
It's fixed.

**Comment by salcido** [comment]
ah nice, looks like it went out sometime late last night / early this morning 👍 
Thanks for taking the time to open an issue!
