### ISSUE TITLE
Feature Request: Load multiple market pages at the same time

### ISSUE THREAD

**Issue by tydog98** [salcido/discogs-enhancer#253]
So while scrolling through the marketplace with the "sort by total price" option on, prices are per page and not continuous. This means you'll scroll past low prices to high prices back to high prices. It would be nice if multiple pages could be loaded at once so everything can be in order.

**Comment by salcido** [comment]
@tydog98 It's not possible to do that, unfortunately. The extension can only access the results returned by Discogs and cannot query Discogs for page results sorted by price. If you open up the Learn page and read the `Sort By Total Price` section you'll see this limitation is called out: 

<img width="527" alt="Screenshot 2023-09-18 at 5 57 03 PM" src="https://github.com/salcido/discogs-enhancer/assets/12960237/8a731399-60ab-482c-ab20-92b534824803">

**Comment by tydog98** [comment]
I see
