### ISSUE TITLE
Push history "page" search parameter in everlasting pages

### ISSUE THREAD

**Issue by nmussy** [salcido/discogs-enhancer#31]
Everlasting collection and marketplace pages should update the current URI using the [History API](https://developer.mozilla.org/en-US/docs/Web/API/History_API)'s push or replaceState method, to allow the user to reload on the current page.

I can make a PR for it if needed.

**Comment by salcido** [comment]
@nmussy Just to clarify - you want the URI to update the `page` param whilst scrolling?

i.e.: 

- You begin at `page 1` and scroll to `page 2`
- URI updates with `&page=2`
- Scroll to `page 3`
- URI updates with `&page=3`
- Scroll back to `page 2`
- URI updates with `&page=2`
- Scroll back to `page 1`
- URI updates with `&page=1`

Is that correct?

**Comment by salcido** [comment]
Ok, I merged a fix for `everlasting marketplace` but the collection will take a few more days since I need to test with a user who has more than 2500 items in their collection. I'm going to test these updates and make sure nothing is broken then I'll push out an update.

**Comment by nmussy** [comment]
Yes, what you describe was what I had in mind.

And I agree about the backwards scrolling, it would have been nice to have, but it's definitely not as important.

**Comment by salcido** [comment]
I pushed out an update to the Chrome web store. It should update automatically sometime in the next 24 hours. New version is `2.14.1`. Let me know if you run into any issues!

**Comment by nmussy** [comment]
I force updated the app, and both issues LGTM. Thanks for the quick response and update!

**Comment by salcido** [comment]
Sure thing :) thanks again for opening up the issues!
