### ISSUE TITLE
Initialize everlasting page index according to search parameter

### ISSUE THREAD

**Issue by nmussy** [salcido/discogs-enhancer#32]
Everlasting pages' page selector index doesn't match the request's search parameter. For example, for [list?page=9](https://www.discogs.com/sell/list?page=9), the Select Page index starts at 1 instead of 9:
![image](https://user-images.githubusercontent.com/2505696/60135130-500bf300-97a1-11e9-91c5-3ee586fec171.png)

Again, I can look into it if needed.
Thanks for the extension!

**Comment by salcido** [comment]
Hey @nmussy,

Thanks so much for taking the time to open up an issue! I should be able to get this working soon. The `everlasting` features are some of the earliest scripts I wrote and, as such, they definitely need to be revisited. I'll get a patch out soon ✌️

**Comment by salcido** [comment]
Ok, should be fixed 👍

**Comment by salcido** [comment]
I pushed out an update to the Chrome web store. It should update automatically sometime in the next 24 hours. New version is `2.14.1`. Let me know if you run into any issues!
