### ISSUE TITLE
Handle Ctrl/Shift + click on "Random item" button

### ISSUE THREAD

**Issue by nmussy** [salcido/discogs-enhancer#43]
The "Random item" button doesn't act like a regular anchor with an href, and it's a little frustrating to have the current page be forcibly replaced. 

You could add to your event listener support for the [`ctrlKey`](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/ctrlKey) and [`shiftKey`](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/shiftKey) properties, to open the random item in a new tab, and a new window respectively:

https://github.com/salcido/discogs-enhancer/blob/0c3f918160a83fe0ad6e663aefa8ac28dfed427c/js/extension/features/random-item.js#L76

Still a pleasure to use your extension, thanks for the continued hard work 👍

**Comment by nmussy** [comment]
Oh, and it's a small nitpick, but I don't think "recycling" Unicode symbol is the clearest representation of a random element. I think either the [gamedie (🎲)](https://graphemica.com/%F0%9F%8E%B2) or [twisted rightwards arrows(🔀)](https://graphemica.com/%F0%9F%94%80) character would be easier for new users to understand

**Comment by salcido** [comment]
Hey @nmussy,

That's a good call, I can update that to a proper `anchor` so it can be opened in separate tags. 

As for the icon, I initially wanted to use the `twisted rightwards arrows` but Chrome (or OS X, not sure which) automatically uses the Emoji version which does not match Discogs style guide. Personally, I don't think Emoji should represent UI elements, so I went with the `recycling` icon since it was a better match with Discogs' style guide aesthetics. 

I may be able to use the Dice icon that is currently used in the React version of the Collection. I'll poke around a bit and see what I can come up with. 

Thanks for the suggestions!

**Comment by nmussy** [comment]
Hey @salcido,

Yeah, I suggested looking at the event properties because it seemed simpler/more efficient than pre-rendering the anchor with the correct URL. But if you can manage it, it'd also fix the context menu "Open 
in a new tab", "new window" etc.

And fair enough for the emoji forms, but you can always force [the VS15 text variant](https://mts.io/2015/04/21/unicode-symbol-render-text-emoji/) by appending `&#xFE0E;` to the unicode character, e.g. `&#x1F3B2;&#xFE0E;`

--


`.

**Comment by salcido** [comment]
>And fair enough for the emoji forms, but you can always force the VS15 text variant by appending &#xFE0E; to the unicode character, e.g. &#x1F3B2;&#xFE0E;

TIL. That's pretty cool! I messed around a bit with that but still wasn't able to force the plain text version. Think I'll make an SVG of the `twisted rightwards arrow` icon as I like that a bit more than the `gamedie`.

While looking into this I realized Discogs has a specific URL just for random items so I'm able to simplify the script quite a bit and ditch the old `async` POST method I was using previously.

**Comment by nmussy** [comment]
That's unfortunate about the text varient, it works perfectly well on Chrome/Windows 10 :

![image](https://user-images.githubusercontent.com/2505696/61271471-02cde080-a7a5-11e9-8b42-81bbac1f9451.png)

And glad to hear about the random URL

**Comment by salcido** [comment]
Ok, just published an update to address this! Going to close this ticket ✌️

**Comment by nmussy** [comment]
Thanks!
