### ISSUE TITLE
Feature request: Whitelist and blacklist continents

### ISSUE THREAD

**Issue by nmussy** [salcido/discogs-enhancer#45]
Hey @salcido,

I just thought of a nice quality of life improvement. It'd be nice to quickly add to the shipping countries list white or blacklist whole continents. The list would still effectively only contain countries, but you could select a continent and add all its states to your list. It's not particularly a problem with North America, but having to whitelist all countries of other continents can be a bit of a pain.

You could use [Wikipedia's list of states by continent](https://en.wikipedia.org/wiki/List_of_sovereign_states_and_dependent_territories_by_continent_(data_file)) as reference.

**Comment by salcido** [comment]
Interesting idea! I'll have to think about this a bit. Currently, you can set the country filter to only `include` specific countries. Might be easier to just add the countries you do want to buy from (assuming that's a shorter list) rather than blocking entire continents? 🤔

**Comment by nmussy** [comment]
Yes you absolutely could, but that's what I meant when I said North America was clearly better suited for that solution. Having to whitelist all South American, European, African or Asian countries manually is much more of a pain.
Living in Europe, I ended up doing was blacklist the most popular countries outside the EU, but I still get the occasional seller from an infrequent country I haven't added to the list.
