### ISSUE TITLE
Bug: "Random item" keeps spinning when you open a new tab

### ISSUE THREAD

**Issue by nmussy** [salcido/discogs-enhancer#58]
Hey @salcido,

I just saw the new "Random item" button, looks much nicer. There's a small bug though, when I Ctrl  + Click it on Chrome, the animation doesn't stop until I `mouseleave` and `mouseenter`, and even then it's kind of inconsistent. Stopping the animation on click should fix that.

Thanks again!

**Comment by salcido** [comment]
It should timeout after 4 seconds:

https://github.com/salcido/discogs-enhancer/blob/master/js/extension/features/random-item.js#L97

**Comment by nmussy** [comment]
So that's why that felt inconsistent 😄 Maybe 4 seconds is too long of an animation, and that's why it felt like a bug?

**Comment by salcido** [comment]
Well, it's definitely working as it should but I'll add a check for `event.metaKey` and shorten the animation duration for you. 👍

**Comment by nmussy** [comment]
Yeah, sorry about that. Thanks for the change ❤️

**Comment by salcido** [comment]
Ok, going to publish an update for this! New version is `2.17.1`. Thanks again for the feedback, I super appreciate it!
